added -t time sync synchornize exit codes bash update --chongo

diff --git a/switchdir b/switchdir
--- a/switchdir
+++ b/switchdir
@@ -2,13 +2,19 @@
 #
 # switchdir - switch a directory symlink to a new directory
 #
+# @(#) $Revision: 1.3 $
+# @(#) $Id: switchdir,v 1.3 2010/03/07 01:24:12 chongo Exp $
+# @(#) $Source: /usr/local/src/cmd/switchdir/RCS/switchdir,v $
+#
 # usage:
-#	switchdir newdir symdir dir1 dir2
+#	switchdir [-t] newdir symdir dir1 dir2
+#
+#	-t		time sync identical files to oldest time
 #
 #	newdir		the new directory to which symdir should point
-#	symdir		a symlink that point to dir1 or dir2
-#	dir1		either the current or previous dir pointed to by symdir
-#	dir2		either the previous or current dir pointed to by symdir
+#	symdir		a symlink that points to dir1 or dir2
+#	dir1		either the current or previous directory pointed to by symdir
+#	dir2		either the previous or current directory pointed to by symdir
 #
 # This tool will cause symdir to point at newdir by replacing dir1 or dir2
 # with newdir.   The replacement selection of dir1 or dir2 depends on which
@@ -39,12 +45,8 @@
 #	The dir1 and dir2 (or their parent dirs if they do not exist)
 #	    must be in the same file system.
 #	The symdir symlink can be anywhere.
-#
-# @(#) $Revision: 1.2 $
-# @(#) $Id: switchdir,v 1.2 2000/05/27 08:39:11 chongo Exp $
-# @(#) $Source: /usr/local/src/cmd/switchdir/RCS/switchdir,v $
-#
-# Copyright (c) 2000 by Landon Curt Noll.  All Rights Reserved.
+
+# Copyright (c) 2000-2012 by Landon Curt Noll.  All Rights Reserved.
 #
 # Permission to use, copy, modify, and distribute this software and
 # its documentation for any purpose and without fee is hereby granted,
@@ -75,7 +77,12 @@
 # parse args
 #
 export PATH="/bin:/usr/bin"
-if [ $# -ne 4 ]; then
+TIMESYNC=
+if [[ $# -gt 0 && "$1" == "-t" ]]; then
+    shift
+    TIMESYNC=true
+fi
+if [[ $# -ne 4 ]]; then
     echo "usage: $0 newdir symdir dir1 dir2" 1>&2
     exit 1
 fi
@@ -106,38 +113,35 @@ function samefs ()
 
     # parse args
     #
-    if [ $# -ne 2 ]; then
+    if [[ $# -ne 2 ]]; then
 	return 5;
     fi
 
     # return false if neither exist
     #
-    if [ ! -e "$1" -o ! -e "$2" ]; then
+    if [[ ! -e "$1" || ! -e "$2" ]]; then
 	return 2;
     fi
 
     # obtain the file systems, return false on error
-    #
-    fs1=`df -P "$1" 2>/dev/null`
-    if [ $? -ne 0 ]; then
-	return 3;
-    fi
-    fs2=`df -P "$2" 2>/dev/null`
-    if [ $? -ne 0 ]; then
-	return 4;
-    fi
-
     # reduce fs1 and fs2 to only the file system names
     #
-    fs1=`echo "$fs1" | sed -n -e '$s/[	 ].*$//p'`
-    fs2=`echo "$fs2" | sed -n -e '$s/[	 ].*$//p'`
-    if [ -z "$fs1" -o -z "$fs2" ]; then
+    fs1=$(df --portability "$1" 2>/dev/null | tail -1 | awk '{print $NF;}')
+    if [[ $? -ne 0 ]]; then
+	return 3;
+    fi
+    fs2=$(df --portability "$2" 2>/dev/null | tail -1 | awk '{print $NF;}')
+    if [[ $? -ne 0 ]]; then
+	return 4;
+    fi
+    #
+    if [[ -z "$fs1" || -z "$fs2" ]]; then
 	return 6;
     fi
 
     # return true only if both strings match
     #
-    if [ "$fs1" = "$fs2" ]; then
+    if [[ "$fs1" == "$fs2" ]]; then
 	return 0;
     fi
     return 1;
@@ -156,24 +160,24 @@ function newer ()
 {
     # parse args
     #
-    if [ $# -ne 2 ]; then
+    if [[ $# -ne 2 ]]; then
 	# wrong arg count, so just pretend our answer it the 1st arg
 	return 0;
 
     # case: arg2 does not exist
     #
-    elif [ ! -e "$2" ]; then
+    elif [[ ! -e "$2" ]]; then
 	# only arg1 exists, or neither exists so we return arg1 anyway
 	return 0;
 
     # case: arg2 exists but arg1 does not exist
     #
-    elif [ ! -e "$1" ]; then
+    elif [[ ! -e "$1" ]]; then
 	# return as if the 2nd arg is newer
 	return 1;
 
     # case: both exists so return the newer
-    elif [ "$2" -nt "$1" ]; then
+    elif [[ "$2" -nt "$1" ]]; then
 	# 2nd arg is newer
 	return 1;
     fi
@@ -183,6 +187,8 @@ function newer ()
 
 #################
 # firewall checks
+#
+# The args, newdir symdir dir1 dir2, must be directories not paths (no /'s)
 #
 # The newdir must exist and be a directory.  A real directory, not a symlink.
 #
@@ -196,14 +202,29 @@ function newer ()
 # all be in the same directory so that the mv will be an atomic rename.
 #################
 
+# No /'s in args
+#
+case "$newdir" in
+*/*) echo "$0: newdir must not contain a /: $newdir"; exit 2 ;;
+esac
+case "$symdir" in
+*/*) echo "$0: symdir must not contain a /: $symdir"; exit 3 ;;
+esac
+case "$dir1" in
+*/*) echo "$0: dir1 must not contain a /: $dir1"; exit 4 ;;
+esac
+case "$dir2" in
+*/*) echo "$0: dir2 must not contain a /: $dir2"; exit 5 ;;
+esac
+
 # newdir must exist and be a directory, not a symlink to a directory
 #
-if [ -L "$newdir" ]; then
+if [[ -L "$newdir" ]]; then
     echo "$0: newdir: $newdir may not be a symbolic link" 1>&2
-    exit 4
-elif [ ! -d "$newdir" ]; then
+    exit 6
+elif [[ ! -d "$newdir" ]]; then
     echo "$0: newdir: $newdir is not a directory" 1>&2
-    exit 5
+    exit 7
 fi
 
 # object is symdir exists but is not a symlink
@@ -211,50 +232,50 @@ fi
 # We do not want to deal with symlink being a file, dir, special file ...
 # only the same where symdir is a symlink or is missing.
 #
-if [ -e "$symdir" -a ! -L "$symdir" ]; then
+if [[ -e "$symdir" && ! -L "$symdir" ]]; then
     echo "$0: symdir: $symdir exists and is not a symlink" 1>&2
-    exit 6
+    exit 8
 fi
 
 # set edir1 and edir2 to either the dir args that exist, or their dirnames
 # that must exist.  In no case can they be symlinks.
 #
-if [ -e "$dir1" ]; then
+if [[ -e "$dir1" ]]; then
     edir1="$dir1"
 else
-    edir1=`dirname "$dir1"`
+    edir1=$(dirname "$dir1")
 fi
 #
-if [ -z "$edir1" -o ! -e "$edir1" ]; then
+if [[ -z "$edir1" || ! -e "$edir1" ]]; then
     echo "$0: dir1: $dir1 does not exist, nor does its parent directory" 1>&2
-    exit 7
-fi
-if [ -L "$edir1" ]; then
-    echo "$0: dir1: $dir1 is a symlink or its parent is a symlink" 1>&2
-    exit 8
-fi
-#
-if [ -e "$dir2" ]; then
-    edir2="$dir2"
-else
-    edir2=`dirname "$dir2"`
-fi
-#
-if [ -z "$edir2" -o ! -e "$edir2" ]; then
-    echo "$0: dir2: $dir2 does not exist, nor does its parent directory" 1>&2
     exit 9
 fi
-if [ -L "$edir2" ]; then
-    echo "$0: dir2: $dir2 is a symlink or its parent is a symlink" 1>&2
+if [[ -L "$edir1" ]]; then
+    echo "$0: dir1: $dir1 is a symlink or its parent is a symlink" 1>&2
     exit 10
+fi
+#
+if [[ -e "$dir2" ]]; then
+    edir2="$dir2"
+else
+    edir2=$(dirname "$dir2")
+fi
+#
+if [[ -z "$edir2" || ! -e "$edir2" ]]; then
+    echo "$0: dir2: $dir2 does not exist, nor does its parent directory" 1>&2
+    exit 11
+fi
+if [[ -L "$edir2" ]]; then
+    echo "$0: dir2: $dir2 is a symlink or its parent is a symlink" 1>&2
+    exit 12
 fi
 
 # dir1 and dir2 must be on the same file systems if they both exist
 # if either does not exist, then their parent directory file system must match
 #
 if ! samefs "$edir1" "$edir2"; then
-    echo "$0: dir1: $dir1 and dir2: $dir2 are or cannot be in same fs" 1>&2
-    exit 11
+    echo "$0: dir1: $dir1 and dir2: $dir2 or their parents on different filesystems" 1>&2
+    exit 13
 fi
 
 #################
@@ -266,18 +287,18 @@ fi
 # we will replace the older if dir1 or dir2 or replace the one that is
 # missing or replace dir1 (in the case of both are missing).
 #
-if [ ! -e "$symdir" -a ! -L "$symdir" ]; then
+if [[ ! -e "$symdir" && ! -L "$symdir" ]]; then
     if newer "$dir1" "$dir2"; then
 	ln -s -f "$dir1" "$symdir"
-	if [ $? -ne 0 ]; then
+	if [[ $? -ne 0 ]]; then
 	    echo "$0: cannot initially: ln -s -f $dir1 $symdir" 1>&2
-	    exit 13
+	    exit 14
 	fi
     else
 	ln -s -f "$dir2" "$symdir"
-	if [ $? -ne 0 ]; then
+	if [[ $? -ne 0 ]]; then
 	    echo "$0: cannot initially: ln -s -f $dir2 $symdir" 1>&2
-	    exit 14
+	    exit 15
 	fi
     fi
 fi
@@ -302,30 +323,30 @@ fi
 
 # case: symdir currently points at dir1 - move newdir in the place of dir2
 #
-if [ "$symdir" -ef "$dir1" ]; then
+if [[ "$symdir" -ef "$dir1" ]]; then
 
     # get rid of dir2
     #
     rm -rf "$dir2"
-    if [ -e "$dir2" ]; then
+    if [[ -e "$dir2" ]]; then
 	echo "$0: cannot remove dir2: $dir2" 1>&2
-	exit 15
+	exit 16
     fi
 
     # dir2 does no longer exists, so move newdir into dir2's place
     #
     mv -f "$newdir" "$dir2"
-    if [ $? -ne 0 -o ! -e "$dir2" ]; then
+    if [[ $? -ne 0 || ! -e "$dir2" ]]; then
 	echo "$0: cannot move newdir: $newdir into dir2's place: $dir2" 1>&2
-	exit 16
+	exit 17
     fi
 
     # point symdir at the dir2, the newly renamed newdir
     #
     ln -s -f -n "$dir2" "$symdir"
-    if [ $? -ne 0 -o ! "$dir2" -ef "$symdir" ]; then
+    if [[ $? -ne 0 || ! "$dir2" -ef "$symdir" ]]; then
 	echo "$0: cannot re-symlink: $symdir to dir2: $dir2" 1>&2
-	exit 17
+	exit 18
     fi
 
 # case: symdir currently points at dir2 - move newdir in the place if dir1
@@ -336,25 +357,25 @@ else
     # get rid of dir1
     #
     rm -rf "$dir1"
-    if [ -e "$dir1" ]; then
+    if [[ -e "$dir1" ]]; then
 	echo "$0: cannot remove dir1: $dir1" 1>&2
-	exit 18
+	exit 19
     fi
 
     # dir1 does no longer exists, so move newdir into dir1's place
     #
     mv -f "$newdir" "$dir1"
-    if [ $? -ne 0 -o ! -e "$dir1" ]; then
+    if [[ $? -ne 0 || ! -e "$dir1" ]]; then
 	echo "$0: cannot move newdir: $newdir into dir1's place: $dir1" 1>&2
-	exit 19
+	exit 20
     fi
 
     # point symdir at the dir1, the newly renamed newdir
     #
     ln -s -f -n "$dir1" "$symdir"
-    if [ $? -ne 0 -o ! "$dir1" -ef "$symdir" ]; then
+    if [[ $? -ne 0 || ! "$dir1" -ef "$symdir" ]]; then
 	echo "$0: cannot re-symlink: $symdir to dir1: $dir1" 1>&2
-	exit 20
+	exit 21
     fi
 fi
 
@@ -362,13 +383,42 @@ fi
 # paranioa
 ##########
 
-if [ ! -e "$symdir" -o ! -L "$symdir" ]; then
+if [[ ! -e "$symdir" || ! -L "$symdir" ]]; then
     echo "$0: symdir: $symdir is no longer a symlink that points somewhere" 1>&2
-    exit 21
-fi
-if [ -e "$newdir" ]; then
-    echo "$0: warning: final cleanup of old: $newdir failed" 1>&2
     exit 22
+fi
+if [[ -e "$newdir" ]]; then
+    echo "$0: warning: final cleanup of old: $newdir failed" 1>&2
+    exit 23
+fi
+
+#################
+# time sync of -t
+#################
+
+if [[ -n "$TIMESYNC" ]]; then
+
+    # look for identical files
+    #
+    (cd "$dir1"; find . -type f -print 2>/dev/null) | while read i; do
+
+	# process only if they exist and are identical
+	#
+	if cmp -s "$dir1/$i" "$dir2/$i"; then
+	    if newer "$dir1/$i" "$dir2/$i"; then
+
+		# file from dir1 is newer, touch to older dir2 file time
+		#
+		touch --reference="$dir2/$i" "$dir1/$i"
+
+	    else
+
+		# file from dir2 is newer, touch to older dir1 file time
+		#
+		touch --reference="$dir1/$i" "$dir2/$i"
+	    fi
+	fi
+    done
 fi
 
 ##########
